---
title: ""
page-layout: full
---

::: {.banner}

# Research Software Africa (RSAfrica26)

### The International Conference of Research Software in Africa

25th-28th August, 2026  
(Online)

[Registration](registration.qmd){.btn .btn-primary .btn-lg}

:::

# Welcome to Research Software Africa (RSAfrica26)

Do you want to learn what others are doing in research software in your domain and in other domains? Or do you want to discuss with others how you balance researcher needs with good software practices? Or maybe you are the only person working on research software in your group?

If so, you might want to join us for RSAfrica26, the new Research Software(RS)conference, from the **25th to the 28th of August 2026**. The theme for this year is **"Research Software Without Borders"**, and the hashtag will be #RSAfrica26.

## Working with Research Software Asia Australia, Research Software Latinoamérica, and Equersa

We are thrilled to announce that we are working with two other conferences, the established Research Software Asia Australia (RSAA26) and the new Research Software Latinoamérica (RSLA26)!

We are creating a joint organising committee, while the co-chairs for each conference can still choose what happens at their event.

As part of this joint organising committee, we have created Equersa](https://equersa.org), an umbrella organisation to coordinate conferences and provide a unified front to global funders and stakeholders. 


::: {style="margin-top: 3rem; padding: 2rem; background: #f8f8f8; border-radius: 8px;"}

## Key Dates (Tentative)

| Item | Open | Close |
|------|------|-------|
| Call for Presentations | 30th March | 1st May |
| Call for Accessibility Fellows | 14th May | 26th June |
| Notification of presentations | 7th July | — |
| Call for Session chairs | ASAP | 7th August |
| Call for Reviewers | ASAP | 15th May |
| Micro-grants | 14th May | 10th July |
| Scholarships | 14th May | 14th August |
| Early Bird Registrations | 15th June | 10th July |
| Standard Registrations | 11th July | 14th August |
| Conference | 25th August | 28th August (depending on conference) |


:::

## Call for Presentations

The Call for Presentations (CFP) for the Research Software Africa Conference 2026 (RSAfrica26) will be announced soon. This year's theme, **"Research Software Without Borders"**, focuses on fostering collaboration and engagement within the research software community.

For more details, please refer to the [Call for Presentations](call_for_presentations.qmd) document when available.

## Call for Workshops

We invite proposals for workshops to be held on the first day of RSAfrica26 (Tuesday, 25th August 2026), focusing on interactive, skills-focused sessions that engage participants in hands-on learning, tool development, or collaborative discussions within the research software community.


### Author Guidelines

Thank you for your interest in contributing to the Research Software Africa Conference 2026 (RSAfrica26). To ensure a smooth submission and presentation experience, please follow the guidelines provided in the [Author Guidelines](author_guidelines.qmd) document.

## Accessibility and Inclusivity

We are committed to creating a safe, accessible, and inclusive environment for all participants. 

In 2022, [Liz Hare](https://twitter.com/DogGeneticsLLC) provided a [high-level accessibility report for the conference](RSEAUNZAccessibility.html) that we use as a benchmark for our performance. 

To this end we are offering scholarships for staff or students to participate for free, as well as 10 accessibility micro-grants valued at $50 AUD to help with internet, headphones, childcare etc. 

Eligibility for the scholarships will be based on prioritising and maximising the inclusion and participation of people who have been impacted due to the cumulative effects of discrimination on factors such as race, gender, disability, gender identity, financial status, and the intersectionality of that discrimination, as well as others not mentioned here.

Eligibility for the accessibility micro-grants will be based on a similar approach.

We encourage participants to apply even if they do not think they are eligible, as this will allow us to prioritise and maximise diversity and inclusion. All information will be treated in a confidential manner.

You will need to provide one short paragraph to explain how you will benefit from the scholarship or micro-grant.

All successful recipients of scholarships and accessible micro-grants are expected to submit a poster for the event.

If you feel that the conference is not matching up to the commitment of these ideals, please let us know by contacting the organising committee at info at rseaa.org.

You can also apply to be an Accessibility Fellow. The RSAA26 Accessibility Fellowship aims to encourage individuals with disabilities - such as those who are deaf, hard of hearing, blind, have low vision, or have other disabilities - from within our community or adjacent communities to join RSAA26. Their involvement will help ensure we are held accountable for the accessibility of this online event.

## Organising Committee Members

- Peculiar C. Umeh
- Michael Umeokoli
- Kim Martin
- Maryblessing Okoli
- Rowland Mosbergen 


## Want to sign up for updates? 

- [Click here to sign up for the RSAA mailing list](https://forms.gle/6YdKBMNX19vniVmk8)
- [Click here to follow us on LinkedIn](https://www.linkedin.com/company/rseaa/)
- [Click here to follow us on Mastodon](https://fediverse.au/@RSEAA)


## Code of Conduct

[The Code of Conduct](https://rse-aunz.github.io/code-of-conduct) is designed to provide all participants with community participation guidelines.


## Contact Us
If you would like to know more or have any questions, please contact the organising committee at info@rseaa.org by email.

## Marketing materials

[Our marketing materials for RSAA26 are here](/marketing).


## Previous RSEAA conferences

- [Click here to view the 2025 conference](/RSEAA25).
- [Click here to view the 2024 conference](/RSEAA24).
- [Click here to view the 2023 conference](/RSEAA23).
- [Click here to view the 2022 conference](/RSEAA22).

## Sponsors
We thank the organizations that make this event possible


<p style="font-size: small;color: grey">
*The <a href="https://cmt3.research.microsoft.com">Microsoft CMT service</a> was used for managing the peer-reviewing process for this conference. This service was provided for free by Microsoft, and they bore all expenses, including costs for Azure cloud services as well as for software development and support.*
</p>
